--Task 01.

CREATE DATABASE Airport

GO

CREATE TABLE Passangers
(
	Id INT PRIMARY KEY IDENTITY,
	FullName VARCHAR(100) UNIQUE NOT NULL,
	Email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Passangers
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName VARCHAR(30) UNIQUE NOT NULL,
	LastName VARCHAR(30) UNIQUE NOT NULL,
	Age TINYINT NOT NULL CHECK(Age >= 21 AND Age <=62),
	Rating DECIMAL  CHECK(Rating >= 0.0 AND Rating <= 10.0)
)