--CREATE DATABASE Zoo

GO

--USE Zoo

GO

--Task 01.
CREATE TABLE Owners
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(50) NOT NULL,
	Address VARCHAR(50) 
)


CREATE TABLE AnimalTypes
(
	Id INT PRIMARY KEY IDENTITY,
	AnimalType VARCHAR(30) NOT NULL,
)

CREATE TABLE Cages
(
	Id INT PRIMARY KEY IDENTITY,
	AnimalTypeId INT FOREIGN KEY REFERENCES AnimalTypes (Id) NOT NULL
)

CREATE TABLE Animals
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(30) NOT NULL,
	BirthDate DATE NOT NULL,
	OwnerId INT FOREIGN KEY REFERENCES Owners (Id),
	AnimalTypeId INT FOREIGN KEY REFERENCES AnimalTypes (Id) NOT NULL,
)

CREATE TABLE Animals
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(30) NOT NULL,
	BirthDate DATE NOT NULL,
	OwnerId INT FOREIGN KEY REFERENCES Owners (Id),
	AnimalTypeId INT FOREIGN KEY REFERENCES AnimalTypes (Id) NOT NULL,
)


CREATE TABLE AnimalCages
(
	CageId INT FOREIGN KEY REFERENCES Cafes(Id),
	AnimalId INT FOREIGN KEY REFERENCES Animals(Id),
	PRIMARY KEY(CageId, AnimalId)
)

CREATE TABLE VolunteersDepartments
(
	Id INT PRIMARY KEY IDENTITY,
	DepartmentName VARCHAR(30) NOT NULL,
)

CREATE TABLE Volunteers
(
	Id INT PRIMARY KEY IDENTITY,
	Name VARCHAR(50) NOT NULL,
	PhoneNumber VARCHAR(15) NOT NULL,
	Address VARCHAR(50),
	AnimalId INT FOREIGN KEY REFERENCES Animals(Id),
	DepartmentId INT FOREIGN KEY REFERENCES VolunteersDepartments(Id)
)



--Task 02.

INSERT INTO Animals
([Name],BirthDate,OwnerId,AnimalTypeId
VALUES
('Giraffe', '2018-09-21', 21, 1),
('Harpy Eagle', '2018-09-21', 15, 3),
('Giraffe', '2018-09-21', 21, 1),
('Giraffe', '2018-09-21', 21, 1),

