CREATE TABLE [ItemTypes](
	[ItemTypeID] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50)
)

CREATE TABLE [Items](
	[ItemID] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50),
	[ItemTypeID] INT FOREIGN KEY REFERENCES [ItemTypes](ItemTypeID)
)

CREATE TABLE [Cities](
	[CityID] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50)
)

CREATE TABLE [Customers](
	[CustomerID] INT PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Birthday] DATETIME2 NOT NULL,
	[CityID] INT FOREIGN KEY REFERENCES [Cities](CityID)
)

CREATE TABLE [Orders](
	[OrderID] INT PRIMARY KEY NOT NULL,
	[CustomerID] INT FOREIGN KEY REFERENCES [Customers](CustomerID) NOT NULL,
)

CREATE TABLE [OrderItems](
	[OrderID] INT FOREIGN KEY REFERENCES [Orders](OrderID) NOT NULL,
	[ItemID] INT FOREIGN KEY REFERENCES [Items](ItemID)
)

